README.md

Add badge that shows the last version number published to npm
and publish time

readme: add npm badge

---

package.json

handles setups where user has overridden prefix in npmrc
fixes #15

update `requireg` 

---

package.json

fix(package): update cacache to version 10.0.4

---

package.json

fix(package): update pacote to version 7.4.2

---

package.json

fix(package): update pacote to version 7.5.3

---

package.json

fix(package): update pacote to version 7.6.1

---

package.json

fix(package): update pacote to version 8.1.5

---

package.json

fix(package): update cacache to version 11.2.0

---

package.json

fix(package): update pacote to version 9.2.3

---

package.json

fix(package): update semver to version 6.2.0

---

package.json

fix(package): update pacote to version 9.5.4

---

package.json

fix(package): update cacache to version 12.0.2

---

package.json

fix(package): update pacote to version 9.5.8

---

package.json

fix(package): update pacote to version 10.1.1

---

package.json

fix(package): update pacote to version 11.1.0

---

package.json

fix(package): update pacote to version 11.1.2

---

package.json

fix(package): update pacote to version 11.1.4

---

package.json

fix(package): update semver to version 7.2.1

---

package.json

fix(package): update semver to version 7.3.2

---

package.json

fix(package): update pacote to version 11.1.6

---

package.json

fix(package): update pacote to version 11.1.8

---

package.json

fix(package): update cacache to version 15.0.3
